#!/bin/bash

API="Rhj7PLqvTh8AYgvcstCcKUuS0lKBD4l5D5VcMDsM"

rm /tmp/json 2> /dev/null
rm /tmp/ipcheck 2> /dev/null

IP=$(echo $1 | tr -d ' ')


REC=`date "+%b %d %Y %H:%M:%S"`" BAD "$IP
REC2=`date "+%b %d %Y %H:%M:%S"`" GOOD "$IP

JSON=$(curl -s https://www.abuseipdb.com/check/$IP/json?key=$API&days=1)
echo $JSON > /tmp/json
cat /tmp/json | python -mjson.tool > /tmp/ipcheck


	rating=$( jq '.[].abuseConfidenceScore' /tmp/ipcheck)


readarray -t lines < <(echo "$rating")
val=$"${lines[0]}"


	if [ -z "$val" ]

	then

		sed -i '/'"$IP"'/d' /etc/fail2ban/bad.ip
		sed -i '/'"$IP"'/d' /etc/fail2ban/good.ip
		printf \ >> /etc/fail2ban/good.ip
		echo $REC2 >> /etc/fail2ban/good.ip

	else
			if [ $val -ge 25 ]
			then

			sed -i '/'"$IP"'/d' /etc/fail2ban/good.ip
			sed -i '/'"$IP"'/d' /etc/fail2ban/bad.ip
			printf  \  >> /etc/fail2ban/bad.ip
			echo $REC >> /etc/fail2ban/bad.ip

			else
			sed -i '/'"$IP"'/d' /etc/fail2ban/bad.ip
			sed -i '/'"$IP"'/d' /etc/fail2ban/good.ip
			printf  \ >> /etc/fail2ban/good.ip
			echo $REC2 >> /etc/fail2ban/good.ip

			fi

	fi


awk '!seen[substr($0,15)]++' /etc/fail2ban/bad.ip > /tmp/tmpBB && mv /tmp/tmpBB /etc/fail2ban/bad.ip


