#!/bin/bash

#updater dns blacklistu FZŠ

ver="0.7.6 stable"

cd /home/dnsblocker
check="0"
TYPE="FORCE"

#root check
        MYUID=$(id -u)
        if [ x$MYUID != x0 ]
          then
            printf -v cmd_str '%q ' "$0" "$@"
            exec sudo su -c "$cmd_str"
          fi

#parametry spušnění

        if [ "$1" = "-d" ]
        then
            TYPE="DAILY"
        fi


        if [ "$1" = "-g" ]
        then
            TYPE="GIT"
        fi


        if [ "$1" = "-c" ]
        then

        cd /home/dnsblocker/github
        git pull
        cd ..

        cmp  /home/dnsblocker/cache/blacklist /home/dnsblocker/github/blacklist || check="1" && TYPE="GIT"
        cmp  /home/dnsblocker/cache/whitelist /home/dnsblocker/github/whitelist || check="1" && TYPE="GIT"

        fi

        if  [ "$1" = "-c" ] && [ "$check" != "1" ]

        then
                echo Git bezezměn, hotovo
                exit
        fi

status="OK"
rm status.txt
touch status.txt

clear

echo =====================================
echo DNS Blacklist generator V$ver
echo =====================================
echo updater spuštěn v režimu $TYPE
echo stahování aktualizací
# blacklist UT1 zdroj 1

        rm adult.tar.gz 2> /dev/null
        rm -rf adult 2> /dev/null
        wget http://adsi.ut-capitole.fr/blacklists/download/adult.tar.gz -q -c --show-progress --content-on-error --retry-connrefused --waitretry=5 --tries=100 --read-timeout=20 --timeout=150

                file="adult.tar.gz"
                if [ -f "$file" ]
                        then
                                echo ""
                        else
                                mtime=$(stat -c "%y" /home/dnsblocker/cache/adult.tar.gz)
                                echo "Problém při stažení $file Beru ze zálohy !! "
                                cp  /home/dnsblocker/cache/adult.tar.gz /home/dnsblocker/
                                status="CHYBA"
                                echo "Chyba zdroje UT1 https://dsi.ut-capitole.fr/blacklists/index_en.php" >> status.txt
                                echo "Použita záloha 1" $mtime >> status.txt

                        fi

                tar -xvzf adult.tar.gz > /dev/null
                cp /home/dnsblocker/adult/domains /home/dnsblocker/
                rm -rf adult 2> /dev/null
                mv domains UT1

                var=$(comm -3 /home/dnsblocker/cache/UT1 /home/dnsblocker/UT1 2> /dev/null | wc -l)
                cmp --silent /home/dnsblocker/cache/UT1 /home/dnsblocker/UT1 || echo "Zdroj 1 (UT adult blacklist) aktualizován. ($var změn)" >> status.txt

                rm  /home/dnsblocker/cache/UT1 2> /dev/null
                cp  /home/dnsblocker/UT1 /home/dnsblocker/cache/

                rm  /home/dnsblocker/cache/adult.tar.gz 2> /dev/null
                cp  /home/dnsblocker/adult.tar.gz  /home/dnsblocker/cache/


# black list na black list :) zdroj 2

        rm hosts 2> /dev/null
        wget https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts -q -c --show-progress --content-on-error --retry-connrefused --waitretry=5 --tries=100 --read-timeout=20 --timeout=150

                file="hosts"
                if [ -f "$file" ]
                        then
                                echo ""
                        else
                                mtime=$(stat -c "%y" /home/dnsblocker/cache/bblock)
                                echo "Problém při stažení $file Beru ze zálohy !!"
                                cp  /home/dnsblocker/cache/bblock /home/dnsblocker/
                                mv bblock hosts
                                status="CHYBA"
                                echo "Chyba zdroje StevenBlack https://github.com/StevenBlack/hosts" >> status.txt
                                echo "Použita záloha 2" $mtime >> status.txt
                        fi

                        mv hosts bblock

                        var=$(comm -3 /home/dnsblocker/cache/bblock /home/dnsblocker/bblock 2> /dev/null | wc -l)
                        cmp --silent /home/dnsblocker/cache/bblock /home/dnsblocker/bblock || echo "Zdroj 2 (malware blacklist) aktualizován. ($var změn)" >> status.txt

                rm  /home/dnsblocker/cache/bblock 2> /dev/null
                cp  /home/dnsblocker/bblock  /home/dnsblocker/cache/


# porn a adds .. musi byt opraven zdroj 3

        rm hosts 2> /dev/null
        wget https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts -q -c --show-progress --content-on-error   --retry-connrefused --waitretry=5 --tries=100 --read-timeout=20 --timeout=150

                file="hosts"
                if [ -f "$file" ]
                        then
                                echo ""
                        else
                               mtime=$(stat -c "%y" /home/dnsblocker/cache/bbad)
                               echo "Problém při stažení $file Beru ze zálohy !!"
                               cp  /home/dnsblocker/cache/bbad /home/dnsblocker/
                               mv bbad hosts
                               status="CHYBA"
                               echo "Chyba zdroje StevenBlack https://github.com/StevenBlack/hosts/tree/master/alternates/porn" >> status.txt
                               echo "Použita záloha 3" $mtime >> status.txt
                        fi

                        mv hosts bbad

                        var=$(comm -3 /home/dnsblocker/cache/bbad /home/dnsblocker/bbad 2> /dev/null | wc -l)
                        cmp --silent /home/dnsblocker/cache/bbad /home/dnsblocker/bbad || echo "Zdroj 3 (porn blacklist) aktualizován. ($var změn)" >> status.txt

                rm  /home/dnsblocker/cache/bbad 2> /dev/null
                cp  /home/dnsblocker/bbad  /home/dnsblocker/cache/


# ads zdroj 4
        rm ad_servers.txt 2> /dev/null
        wget https://hosts-file.net/ad_servers.txt -q -c --show-progress --content-on-error --retry-connrefused --waitretry=5 --tries=100 --read-timeout=20 --timeout=150

                file="ad_servers.txt"
                if [ -f "$file" ]
                        then
                                echo ""
                        else
                               mtime=$(stat -c "%y" /home/dnsblocker/cache/ad_servers.txt)
                               echo "Problém při stažení $file Beru ze zálohy !!"
                               cp  /home/dnsblocker/cache/ad_servers.txt /home/dnsblocker/
                               status="CHYBA"
                               echo "Chyba zdroje ADS (reverse) https://hosts-file.net/ad_servers.txt" >> status.txt
                               echo "Použita záloha 4" $mtime >> status.txt
                        fi

                                var=$(comm -3 /home/dnsblocker/cache/ad_servers.txt /home/dnsblocker/ad_servers.txt 2> /dev/null | wc -l)
                                cmp --silent /home/dnsblocker/cache/ad_servers.txt /home/dnsblocker/ad_servers.txt || echo "Zdroj 4 (ads reverse blacklist) aktualizován. ($var změn)" >> status.txt

                rm  /home/dnsblocker/cache/ad_servers.txt 2> /dev/null
                cp  /home/dnsblocker/ad_servers.txt  /home/dnsblocker/cache/



# porn hosts zdroj 5
        rm hosts 2> /dev/null
        wget https://raw.githubusercontent.com/EnergizedProtection/block/master/porn/formats/hosts -q -c --show-progress --content-on-error --retry-connrefused --waitretry=5 --tries=100 --read-timeout=20 --timeout=150

                file="hosts"
                if [ -f "$file" ]
                        then
                                echo ""
                        else
                                mtime=$(stat -c "%y" /home/dnsblocker/cache/hosts2)
                                echo "Problém při stažení $file Beru ze zálohy !!"
                                cp  /home/dnsblocker/cache/hosts2 /home/dnsblocker/
                                mv hosts2 hosts
                                status="CHYBA"
                                echo "Chyba zdroje EnergizedProtection porn https://github.com/EnergizedProtection/block" >> status.txt
                                echo "Použita záloha 5" $mtime >> status.txt
                        fi

                        mv hosts hosts2

                                var=$(comm -3 /home/dnsblocker/cache/hosts2 /home/dnsblocker/hosts2 2> /dev/null | wc -l)
                                cmp --silent /home/dnsblocker/cache/hosts2 /home/dnsblocker/hosts2 || echo "Zdroj 5 (Energized porn blacklist) aktualizován. ($var změn)" >> status.txt

                rm  /home/dnsblocker/cache/hosts2 2> /dev/null
                cp  /home/dnsblocker/hosts2  /home/dnsblocker/cache/


# a jeste jeden ciste porn zdroj 6
        rm hosts 2> /dev/null



        wget https://raw.githubusercontent.com/EnergizedProtection/block/master/extensions/porn-lite/formats/hosts -q -c --show-progress --content-on-error --retry-connrefused --waitretry=5 --tries=100 --read-timeout=20 --timeout=150

                file="hosts"
                if [ -f "$file" ]
                        then
                                echo ""
                        else
                                mtime=$(stat -c "%y" /home/dnsblocker/cache/ext-porn-hosts)
                                echo "Problém při stažení $file beru ze zálohy !!"
                                cp  /home/dnsblocker/cache/ext-porn-hosts /home/dnsblocker/
                                mv ext-porn-hosts hosts
                                status="CHYBA"
                                echo "Chyba zdroje EnergizedProtection porn extension https://github.com/EnergizedProtection/block" >> status.txt
                                echo "Použita záloha 6" $mtime >> status.txt
                        fi

                        mv hosts ext-porn-hosts

                                var=$(comm -3 /home/dnsblocker/cache/ext-porn-hosts /home/dnsblocker/ext-porn-hosts 2> /dev/null | wc -l)
                                cmp --silent /home/dnsblocker/cache/ext-porn-hosts /home/dnsblocker/ext-porn-hosts || echo "Zdroj 6 (Energized porn extra blacklist) aktualizován. ($var změn)" >> status.txt

                rm  /home/dnsblocker/cache/ext-porn-hosts 2> /dev/null
                cp  /home/dnsblocker/ext-porn-hosts  /home/dnsblocker/cache/


# malware zdroj 7
        rm simple_malware.txt 2> /dev/null
        wget https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt -q -c --show-progress --content-on-error   --retry-connrefused --waitretry=5 --tries=100 --read-timeout=20 --timeout=150

                file="simple_malware.txt"
                if [ -f "$file" ]
                        then
                                echo ""
                        else
                               mtime=$(stat -c "%y" /home/dnsblocker/cache/simple_malware.txt)
                               echo "Problém při stažení $file Beru ze zálohy !!"
                               cp  /home/dnsblocker/cache/simple_malware.txt /home/dnsblocker/
                               status="CHYBA"
                               echo "Chyba zdroje simple malware https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt" >> status.txt
                               echo "Použita záloha 7" $mtime >> status.txt
                        fi

                               var=$(comm -3 /home/dnsblocker/cache/simple_malware.txt /home/dnsblocker/simple_malware.txt 2> /dev/null | wc -l)
                               cmp --silent /home/dnsblocker/cache/simple_malware.txt /home/dnsblocker/simple_malware.txt || echo "Zdroj 7 (malware blacklist) aktualizován. ($var změn)" >> status.txt

                rm  /home/dnsblocker/cache/simple_malware.txt 2> /dev/null
                cp  /home/dnsblocker/simple_malware.txt  /home/dnsblocker/cache/



# megaporn list zdroj 8
        rm porn 2> /dev/null
        wget https://tspprs.com/dl/porn -q -c --show-progress --content-on-error --retry-connrefused --waitretry=5 --tries=100 --read-timeout=20 --timeout=150

                file="porn"
                if [ -f "$file" ]
                        then
                                echo ""
                        else
                               mtime=$(stat -c "%y" /home/dnsblocker/cache/porn)
                               echo "Problém při stažení $file Beru ze zálohy !!"
                               cp  /home/dnsblocker/cache/porn /home/dnsblocker/
                               status="CHYBA"
                               echo "Chyba zdroje simple malware https://tspprs.com/dl/porn" >> status.txt
                               echo "Použita záloha 8" $mtime >> status.txt
                        fi

                               var=$(comm -3 /home/dnsblocker/cache/porn /home/dnsblocker/porn 2> /dev/null | wc -l)
                               cmp --silent /home/dnsblocker/cache/porn /home/dnsblocker/porn || echo "Zdroj 8 (megapornlist) aktualizován. ($var změn)" >> status.txt

                rm  /home/dnsblocker/cache/porn 2> /dev/null
                cp  /home/dnsblocker/porn  /home/dnsblocker/cache/



echo ===================
echo konverze blacklistu
echo ===================

echo whitelistovaní chybného blacklistu

        grep -Fvxf bblock bbad > fresh

echo příprava blacklistu

        sed -i 's/0.0.0.0//g' fresh
        sed -i '/#/d' fresh

echo odstranění komentářů simple malware

        sed -i '/#/d' simple_malware.txt
        sed -i '/Malware list by Disconnect/d' simple_malware.txt
        sed -i '/^$/d' simple_malware.txt
        sed -i -r 's/\s+//g' simple_malware.txt
        echo " " >> simple_malware.txt

echo odstranění ochrany [̲̅p̲̅][̲̅o̲̅][̲̅r̲̅][̲̅n̲̅][̲̅a̲̅][̲̅w̲̅][̲̅a̲̅][̲̅y̲̅] 1/2

        awk '!/]/' ext-porn-hosts > temp && mv temp bingo
        rm ext-porn-hosts 2> /dev/null
        mv bingo ext-porn-hosts

echo odstranění komentů porn hosts2
        sed -i '/#/d' hosts2
echo  odstranění chybných záznamů porn hosts2
        sed -i '/127.0.0.1 localhost/d' hosts2
echo -en 7.1% "\r$i"
        sed -i '/127.0.0.1 localhost.localdomain/d' hosts2
echo -en 14.2% "\r$i"
        sed -i '/127.0.0.1 local/d' hosts2
echo -en 21.4% "\r$i"
        sed -i '/255.255.255.255 broadcasthost/d' hosts2
echo -en 28.5% "\r$i"
        sed -i '/::1 localhost/d' hosts2
echo -en 35.7% "\r$i"
        sed -i '/::1 ip6-localhost/d' hosts2
echo -en 42.8% "\r$i"
        sed -i '/::1 ip6-loopback/d' hosts2
echo -en 50.0% "\r$i"
        sed -i '/fe80::1%lo0 localhost/d' hosts2
echo -en 57.1% "\r$i"
        sed -i '/ff00::0 ip6-localnet/d' hosts2
echo -en 64.2% "\r$i"
        sed -i '/ff00::0 ip6-mcastprefix/d' hosts2
echo -en 71.4% "\r$i"
        sed -i '/ff02::1 ip6-allnodes/d' hosts2
echo -en 78.5% "\r$i"
        sed -i '/ff02::2 ip6-allrouters/d' hosts2
echo -en 85.7% "\r$i"
        sed -i '/ff02::3 ip6-allhosts/d' hosts2
echo -en 92.8% "\r$i"
        sed -i '/0.0.0.0 0.0.0.0/d' hosts2
echo 100%.


echo odstanění prázdných záznamů porn host2s

        sed -i '/^$/d' hosts2
        sed -i -r 's/\s+//g' hosts2

echo úprava záznamů porn hosts2

        sed -i 's/0.0.0.0//g' hosts2


echo odstranění ochrany 2/2


 awk '!/]/' hosts2 > temp && mv temp bingo
        rm hosts2 2> /dev/null
        mv bingo hosts

echo odstranění komentů ext-porn
        sed -i '/#/d' ext-porn-hosts
echo  odstranění chybných záznamů ext-porn
        sed -i '/127.0.0.1 localhost/d' ext-porn-hosts
echo -en 7.1% "\r$i"
        sed -i '/127.0.0.1 localhost.localdomain/d' ext-porn-hosts
echo -en 14.2% "\r$i"
        sed -i '/127.0.0.1 local/d' ext-porn-hosts
echo -en 21.4% "\r$i"
        sed -i '/255.255.255.255 broadcasthost/d' ext-porn-hosts
echo -en 28.5% "\r$i"
        sed -i '/::1 localhost/d' ext-porn-hosts
echo -en 35.7% "\r$i"
        sed -i '/::1 ip6-localhost/d' ext-porn-hosts
echo -en 42.8% "\r$i"
        sed -i '/::1 ip6-loopback/d' ext-porn-hosts
echo -en 50.0% "\r$i"
        sed -i '/fe80::1%lo0 localhost/d' ext-porn-hosts
echo -en 57.1% "\r$i"
        sed -i '/ff00::0 ip6-localnet/d' ext-porn-hosts
echo -en 64.2% "\r$i"
        sed -i '/ff00::0 ip6-mcastprefix/d' ext-porn-hosts
echo -en 71.4% "\r$i"
        sed -i '/ff02::1 ip6-allnodes/d' ext-porn-hosts
echo -en 78.5% "\r$i"
        sed -i '/ff02::2 ip6-allrouters/d' ext-porn-hosts
echo -en 85.7% "\r$i"
        sed -i '/ff02::3 ip6-allhosts/d' ext-porn-hosts
echo -en 92.8% "\r$i"
        sed -i '/0.0.0.0 0.0.0.0/d' ext-porn-hosts
echo 100%.


echo odstanění prázdných záznamů ext-porn

        sed -i '/^$/d' ext-porn-hosts
        sed -i -r 's/\s+//g' ext-porn-hosts

echo úprava záznamů ext-porn

        sed -i 's/0.0.0.0//g' ext-porn-hosts

echo čistění magaporn listu

        sed -i '/^$/d' porn
        sed -i -r 's/\s+//g' porn


echo propojení blacklistů

        sed -i -r 's/\s+//g' perBlacklist
        sed -i '/^$/d' perBlacklist

        rm domainsC 2> /dev/null
        cat ext-porn-hosts hosts simple_malware.txt fresh UT1 porn > domainsC

echo odstranění blogspot záznamů

        sed -i '/blogspot./d' domainsC

echo odstranění tumblr.com záznamů

        sed -i '/tumblr.com/d' domainsC

cat domainsC perBlacklist > domains

echo odstranění nepoužitelných IP

        grep -P -v '^\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}$' domains > domains.list

echo odstranění komentů ADS

        sed -i '/#/d' ad_servers.txt
        sed -i '/127.0.0.1 localhost #IPv4 localhost/d' ad_servers.txt
        sed -i '/::1 localhost #IPv6 localhost/d' ad_servers.txt

echo úprava záznamů ADS

        sed -i 's/127.0.0.1//g' ad_servers.txt
        sed -i '/^$/d' ad_servers.txt
        sed -i -r 's/\s+//g' ad_servers.txt

echo příprava porovnávacího souboru ADS

        sed -i '/^$/d' ad_servers.txt
        sed -i -r 's/\s+//g' ad_servers.txt

        sed -i 's/^/"/' ad_servers.txt
        sed -i 's/$/",/' ad_servers.txt
        sed -i '/^$/d' ad_servers.txt

echo úprava záznamů pro primární BL 1/2

        sed -i 's/$/",/' domains.list

echo úprava záznamů pro primární BL 2/2

        sed -i 's/^/"/' domains.list


echo reversní aplikace ADS

       rm domains.list2 2> /dev/null
       grep -Fvxf ad_servers.txt domains.list > domains.list2


echo aktualizace black/white listu z github

        cd github
        git pull
        cd ..

#       varo=$(grep -f /home/dnsblocker/github/blacklist /home/dnsblocker/github/whitelist | wc -l)

#       if [ "$varo" != "0" ]
#        then

#        echo "Následující záznamy jsou nalezeny duplicitně (jak u whitelist tak u blacklist) :" >> status.txt

#       dup=$(comm -13 <(sort /home/dnsblocker/github/whitelist) <(sort /home/dnsblocker/github/blacklist))

#       echo "$dup" >> status.txt

#        fi

                varb=$(comm -3 /home/dnsblocker/cache/blacklist /home/dnsblocker/github/blacklist 2> /dev/null | wc -l)

                cmp --silent /home/dnsblocker/cache/blacklist /home/dnsblocker/github/blacklist || echo "Ručně změněných záznamů blacklistu : $varb" >> status.txt

                rm  /home/dnsblocker/cache/blacklist 2> /dev/null
                cp  /home/dnsblocker/github/blacklist /home/dnsblocker/cache/


                varw=$(comm -3 /home/dnsblocker/cache/whitelist /home/dnsblocker/github/whitelist 2> /dev/null | wc -l)
                cmp --silent /home/dnsblocker/cache/whitelist /home/dnsblocker/github/whitelist || echo "Ručně změněných záznamů whitelistu : $varw" >> status.txt

                rm  /home/dnsblocker/cache/whitelist 2> /dev/null
                cp  /home/dnsblocker/github/whitelist /home/dnsblocker/cache/


echo generování výstupu blacklistu

        rm blacklist 2> /dev/null
        cp /home/dnsblocker/github/blacklist /home/dnsblocker/

        sed -i '/^$/d' blacklist
        sed -i -r 's/\s+//g' blacklist

        sed -i 's/^/"/' blacklist
        sed -i 's/$/",/' blacklist
        sed -i '/^$/d' blacklist

echo připojení blacklistu z github

        rm blacklisted 2> /dev/null
        cat domains.list2 blacklist > blacklisted
        dos2unix blacklisted -q

echo generování výstupu whitelistu z github

        rm whitelist 2> /dev/null
        cp /home/dnsblocker/github/whitelist /home/dnsblocker/

        cat perWhitelist whitelist > whitelistB
        rm whitelist 2> /dev/null
        mv whitelistB whitelist


        #subdomeny
        rm whitelistD 2> /dev/null
        sed 's/^/./' whitelist > whitelistD

        sed -i '/^$/d' whitelist
        sed -i -r 's/\s+//g' whitelist

        sed -i 's/^/"/' whitelist
        sed -i 's/$/",/' whitelist
        sed -i '/^$/d' whitelist

echo připojení whitelistu

        dos2unix blacklisted -q
        dos2unix whitelistD -q
        dos2unix whitelist -q

        rm blocklistA 2> /dev/null

        grep -vFf whitelistD blacklisted > blacklistD
        grep -Fvxf whitelist blacklistD > blocklist

echo odstanění prázdných záznamů

        sed -i '/^$/d' blocklist
        sed -i -r 's/\s+//g' blocklist

echo oprava nepoužitelných záznamů

        sed -i 's|/"|"|g' blocklist

echo kontrola duplicitních záznamů

        awk '!x[$0]++' blocklist > blocklist.lua

echo seřazení podle abecedy

        sort blocklist.lua -o blocklist.lua

echo kontrola domén

        sed -i '/\./!d' blocklist.lua

echo přidání tagů

        sed -i '1i return{' blocklist.lua
        echo "}" >> blocklist.lua

echo čištění a oprava kompatiblity

        rm adult.tar.gz 2> /dev/null
        rm UT1 2> /dev/null
        rm ad_servers.txt 2> /dev/null
        rm blacklist 2> /dev/null
        rm blacklistD 2> /dev/null
        rm blacklisted 2> /dev/null
        rm blocklist 2> /dev/null
        rm blocklistA 2> /dev/null
        rm domains.list 2> /dev/null
        rm domains.list2 2> /dev/null
        rm ext-porn-hosts 2> /dev/null
        rm domains 2> /dev/null
        rm domainsC 2> /dev/null
        rm hosts 2> /dev/null
        rm bbad 2> /dev/null
        rm bblock 2> /dev/null
        rm fresh 2> /dev/null
        rm simple_malware.txt 2> /dev/null
        rm whitelist 2> /dev/null
        rm whitelistD 2> /dev/null
        rm porn 2> /dev/null
        dos2unix blocklist.lua -q

echo příprava pro zveřejnění

        rm /var/www/html/blocklist.lua 2> /dev/null
        cp /home/dnsblocker/blocklist.lua /var/www/html

        rm /home/dnsblocker/cache/whitelist 2> /dev/null
        cp /home/dnsblocker/github/whitelist /home/dnsblocker/cache

        rm /home/dnsblocker/cache/blacklist 2> /dev/null
        cp /home/dnsblocker/github/blacklist /home/dnsblocker/cache

        pocet=$(sed -n '$=' blocklist.lua)
        size=$(wc -c < "blocklist.lua")
        echo "Počet záznamů :" $pocet >> status.txt
        echo "Velikost blacklistu :" $size"b" >> status.txt

                var=$(comm -3 /home/dnsblocker/cache/blocklist.lua /home/dnsblocker/blocklist.lua 2> /dev/null | wc -l)
                echo "Celkem aplikovaných změn v databázi : $var" >> status.txt

                mv -f /home/dnsblocker/status.txt /home/dnsblocker/github

                rm /home/dnsblocker/cache/blocklist.lua 2> /dev/null
                cp /home/dnsblocker/blocklist.lua /home/dnsblocker/cache/blocklist.lua

echo zveřejnění změn na github

        cd  github

                sed -i '1d' README.md
                sed -i '1 i# FZSDNS '"$ver"'' README.md

        git add .
        git commit -m "$TYPE Update : `date` '$status'" -m "počet záznamů : '$pocet' velikost : '$size'"
     #git commit --amend --no-edit --allow-empty
     #git push --force
        git push

        if [ $var -lt 1 ]
            then
                echo "Hotovo, aktualizace není nutná"
                rm /home/dnsblocker/blocklist.lua 2> /dev/null
                exit
            fi

echo aplikace blacklistu na DNS1 server

        cd ..

        rm /etc/powerdns/blocklist.lua 2> /dev/null
        mv /home/dnsblocker/blocklist.lua /etc/powerdns
#       /etc/init.d/pdns-recursor stop
        echo 3 > /proc/sys/vm/drop_caches
#       /etc/init.d/pdns-recursor start

        rec_control --timeout=90 reload-lua-script


cd /

# dns2 sync

        sshpass -p updater4321 ssh -o StrictHostKeyChecking=no updater@192.168.1.3 "sudo updater2"


echo Hotovo
