#!/bin/bash

cd /home/kerbal/DMPServer

    if [ "$1" = "start" ]
        then

        file="/tmp/ksp.lock"

        if [ -f "$file" ]
                        then
			echo "KSP server již běží"
			exit
        else

            mono-service -l:/tmp/ksp.lock /home/kerbal/DMPServer/DMPServer.exe

        echo "KSP server spuštěn"

                exit
        fi
    fi

    if [ "$1" = "stop" ]
        then

	file="/tmp/ksp.lock"

	if [ -f "$file" ]
                        then
			lock=$(cat "$file") 
			kill "$lock" 
			rm /tmp/ksp.lock 
			echo "KSP server zastaven"
			exit
	else 
	echo "KSP server není spuštěn"
        exit
	fi
    fi

    if [ "$1" = "restart" ]
        then

        file="/tmp/ksp.lock"

	if [ -f "$file" ]
                        then
			lock=$(cat "$file")
        		kill "$lock" 
		        rm /tmp/ksp.lock 

			mono-service -l:/tmp/ksp.lock /home/kerbal/DMPServer/DMPServer.exe

		        echo "KSP server restartován"
			exit
	else
		mono-service -l:/tmp/ksp.lock /home/kerbal/DMPServer/DMPServer.exe
		echo "KSP server spuštěn"

	exit

	fi
    fi

    if [ "$1" = "" ]
        then

        echo "použijte parametry : start/stop/restart/status/update"
	exit

    fi

    if [ "$1" = "status" ]
        then

        file="/tmp/ksp.lock"

        if [ -f "$file" ]
                        then
                        echo "KSP server běží"
			exit
        else
        echo "KSP server není spuštěn"
        exit

        fi

    fi

    if [ "$1" = "update" ]
        then

            mono /home/kerbal/DMPServer/DMPUpdater.exe

                exit
    fi


	echo "chybný parametr"

