#!/bin/bash

cd /home/kerbal/DMPServer

    if [ "$1" = "start" ]
        then
            mono-service -l:/tmp/ksp.lock /home/kerbal/DMPServer/DMPServer.exe

	echo "KSP server spuštěn"

		exit
    fi


    if [ "$1" = "stop" ]
        then

	file="/tmp/ksp.lock"

	if [ -f "$file" ]
                        then
			lock=$(cat "$file") 
			kill "$lock" 
			rm /tmp/ksp.lock 
			echo "KSP server zastaven"
			exit
	else 
	echo "KSP server není spuštěn"
        exit
	fi
    fi

    if [ "$1" = "restart" ]
        then

        file="/tmp/ksp.lock"

	if [ -f "$file" ]
                        then
			lock=$(cat "$file")
        		kill "$lock" 
		        rm /tmp/ksp.lock 

			mono-service -l:/tmp/ksp.lock /home/kerbal/DMPServer/DMPServer.exe

		        echo "KSP server restartován"
			exit

	else

		mono-service -l:/tmp/ksp.lock /home/kerbal/DMPServer/DMPServer.exe

		echo "KSP server spuštěn"

	exit

	fi
    fi

    if [ "$1" = "" ]
        then

        echo "použijte parametry : start/stop/restart"
	exit

    fi

	echo "chybný parametr"

